export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_HOUSING = "LOAD_HOUSING";
export const REMOVE_HOUSING = "REMOVE_HOUSING";
export const LOAD_SINGLE_HOUSING = "LOAD_SINGLE_HOUSING";
export const LOAD_SEARCH_HOUSING = "LOAD_SEARCH_HOUSING";
export const LOAD_RECOMMEND_HOUSING = "LOAD_RECOMMEND_HOUSING";