export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_HOUSES = "LOAD_HOUSES";
export const REMOVE_HOUSES = "REMOVE_HOUSES";
export const LOAD_SEARCH_HOUSES = "LOAD_SEARCH_HOUSES";
export const LOAD_RECOMMEND_HOUSES = "LOAD_RECOMMEND_HOUSES";